context:
  version: 1.0.11
  python_min: 3.10

package:
  name: monsterui
  version: ${{ version }}

source:
- url: https://pypi.org/packages/source/m/monsterui/monsterui-${{ version }}.tar.gz
  sha256: 79aa9aed6168ca87e760feb2bc0e9849622c856bc02f61037ece566312c5e69b

build:
  script: ${{ PYTHON }} -m pip install .
  noarch: python
  number: 0

requirements:
  host:
  - python ${{ python_min }}.*
  - setuptools >=64.0
  - pip
  run:
  - python >=${{ python_min }}
  - python-fasthtml 
  - fastcore 
  - lxml 
  - mistletoe 

tests:
- python:
    imports:
    - monsterui
    pip_check: true
    python_version: ${{ python_min }}

about:
  homepage: https://github.com/AnswerDotAI/MonsterUI
  summary: The simplicity of FastHTML with the power of Tailwind
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
  - moritzwilksch
